name: Pipe Cy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
jobs: 
  regression-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Runner Tests
        uses: cypress-io/github-action@v5
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          NAME: ${{ secrets.NAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          USER_ID: ${{ secrets.USER_ID }}
          build: npm run build
          start: npm run test
