name: Pipe Cy

on:
  push:
  pull_request:
    branches:
      - 'main'

jobs:
  cypress-run:
    name: Execution backend tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout in project
        uses: actions/checkout@v3

      - name: Setup cypress
        uses: cypress-io/github-action@v5
        with:
          build: npm run build
          start: npm run test
        env:
          CYPRESS_BASE_URL: ${{secrets.BASE_URL}}
          CYPRESS_NAME: ${{secrets.NAME}}
          CYPRESS_PASSWORD: ${{secrets.PASSWORD}}
          CYPRESS_USER_ID: ${{secrets.USER_ID}}