name: Pipe

on:
  push:
  pull_request:
    branches:
      - 'main'

jobs:
  regression-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Runner Tests
        uses: cypress-io/github-action@v5
        env:
          CYPRESS_NAME: ${{secrets.NAME}}
          CYPRESS_PASSWORD: ${{secrets.PASSWORD}}
          CYPRESS_USER_ID: ${{secrets.USER_ID}}
          build: npm run build
          start: npm run test
